import React, {useState} from 'react';
import {View, Text, TouchableOpacity, ScrollView} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {styles} from '../theme';
import {useNavigation} from '@react-navigation/native';
import Loading from '../components/loading';
import TrendingMovies from '../components/trendingMovies';
import MovieList from '../components/movieList';
import {MagnifyingGlassIcon} from 'react-native-heroicons/outline';

export default function HomeScreen() {
  const navigation = useNavigation();

  const [loading, setLoading] = useState(false);

  const [trending, setTrending] = useState([
    {
      adult: false,
      backdrop_path: '/lpVA65vmJqHnG6aaoA5d8Tmkqzm.jpg',
      id: 1002185,
      title: 'A Million Miles Away',
      original_language: 'en',
      original_title: 'A Million Miles Away',
      overview:
        'A migrant farmworker, José Hernández, defies all odds to fulfill his lifelong dream of becoming a NASA astronaut and going to space.',
      poster_path: '/kMI3tgxLAZbzGOVlorUBva0kriS.jpg',
      media_type: 'movie',
      genre_ids: [36, 878, 18],
      popularity: 28.813,
      release_date: '2023-09-08',
      video: false,
      vote_average: 7.7,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
      id: 346698,
      title: 'Barbie',
      original_language: 'en',
      original_title: 'Barbie',
      overview:
        'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
      poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
      media_type: 'movie',
      genre_ids: [35, 12, 14],
      popularity: 2929.987,
      release_date: '2023-07-19',
      video: false,
      vote_average: 7.317,
      vote_count: 4453,
    },
    {
      adult: false,
      backdrop_path: '/iiXliCeykkzmJ0Eg9RYJ7F2CWSz.jpg',
      id: 762430,
      title: 'Retribution',
      original_language: 'en',
      original_title: 'Retribution',
      overview:
        'When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the backseat and a bomb that will explode if they get out of the car, an everyday commute becomes a twisted game of life or death as Matt follows the stranger’s increasingly dangerous instructions in a race against time to save his family.',
      poster_path: '/oUmmY7QWWn7OhKlcPOnirHJpP1F.jpg',
      media_type: 'movie',
      genre_ids: [53, 28, 80],
      popularity: 130.661,
      release_date: '2023-08-23',
      video: false,
      vote_average: 5.702,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: '/iIkogEFPujTQT2A35jG5Q5A7chv.jpg',
      id: 353577,
      title: 'Love at First Sight',
      original_language: 'en',
      original_title: 'Love at First Sight',
      overview:
        'Hadley and Oliver begin falling in love on a flight from New York to London, but when they lose each other at customs, can they defy all odds to reunite?',
      poster_path: '/vCMGlarDrcmhclBmnYoH7JUCDuA.jpg',
      media_type: 'movie',
      genre_ids: [10749, 18],
      popularity: 69.933,
      release_date: '2023-09-15',
      video: false,
      vote_average: 7.297,
      vote_count: 32,
    },
    {
      adult: false,
      backdrop_path: '/27smIACMvE6X2kaURxZVT41p51W.jpg',
      id: 1122634,
      title: 'Once Upon a Crime',
      original_language: 'ja',
      original_title: '赤ずきん、旅の途中で死体と出会う。',
      overview:
        'While at the royal ball with Cinderella, Little Red Riding Hood finds herself in the middle of a mystery. Can she solve the case before midnight strikes?',
      poster_path: '/5FFpXoNpHdmx4hYEQOjtgotOH4b.jpg',
      media_type: 'movie',
      genre_ids: [12, 14, 35],
      popularity: 62.665,
      release_date: '2023-09-13',
      video: false,
      vote_average: 7.1,
      vote_count: 20,
    },
    {
      adult: false,
      backdrop_path: '/3tzPSJiCPqacAgRsMkMPof2ZinL.jpg',
      id: 1008042,
      title: 'Talk to Me',
      original_language: 'en',
      original_title: 'Talk to Me',
      overview:
        'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.',
      poster_path: '/kdPMUMJzyYAc4roD52qavX0nLIC.jpg',
      media_type: 'movie',
      genre_ids: [27, 53],
      popularity: 2685.799,
      release_date: '2023-07-26',
      video: false,
      vote_average: 7.194,
      vote_count: 473,
    },
    {
      adult: false,
      backdrop_path: '/w2nFc2Rsm93PDkvjY4LTn17ePO0.jpg',
      id: 614930,
      title: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
      original_language: 'en',
      original_title: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
      overview:
        "After years of being sheltered from the human world, the Turtle brothers set out to win the hearts of New Yorkers and be accepted as normal teenagers through heroic acts. Their new friend April O'Neil helps them take on a mysterious crime syndicate, but they soon get in over their heads when an army of mutants is unleashed upon them.",
      poster_path: '/ueO9MYIOHO7M1PiMUeX74uf8fB9.jpg',
      media_type: 'movie',
      genre_ids: [16, 35, 28],
      popularity: 841.568,
      release_date: '2023-07-31',
      video: false,
      vote_average: 7.261,
      vote_count: 456,
    },
    {
      adult: false,
      backdrop_path: '/bzKzDqV7m8MLWN7G4oZdgIFDHxf.jpg',
      id: 1113448,
      title: 'Ehrengard: The Art of Seduction',
      original_language: 'da',
      original_title: 'Ehrengard: Forførelsens kunst',
      overview:
        'When a self-appointed expert on love tries to teach a timid prince the art of seduction, the plan backfires, leading to scandal — and unexpected romance.',
      poster_path: '/7gXPtMckzLAFOA8V2niy54HqQ4e.jpg',
      media_type: 'movie',
      genre_ids: [10749, 35, 18],
      popularity: 59.284,
      release_date: '2023-09-14',
      video: false,
      vote_average: 7.714,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/c0MTj7GxwuBujjSsdRQ9i1OstLl.jpg',
      id: 991708,
      title: 'El Conde',
      original_language: 'es',
      original_title: 'El Conde',
      overview:
        'Augusto Pinochet is a vampire ready to die, but the vultures around him won’t let him go without one last bite.',
      poster_path: '/b67X0U6puvoPZe20DBdbSXLqxLt.jpg',
      media_type: 'movie',
      genre_ids: [27, 35],
      popularity: 23.104,
      release_date: '2023-09-08',
      video: false,
      vote_average: 6.8,
      vote_count: 20,
    },
    {
      adult: false,
      backdrop_path: '/53z2fXEKfnNg2uSOPss2unPBGX1.jpg',
      id: 968051,
      title: 'The Nun II',
      original_language: 'en',
      original_title: 'The Nun II',
      overview:
        'In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.',
      poster_path: '/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg',
      media_type: 'movie',
      genre_ids: [27, 9648, 53],
      popularity: 1608.611,
      release_date: '2023-09-06',
      video: false,
      vote_average: 6.636,
      vote_count: 169,
    },
    {
      adult: false,
      backdrop_path: '/7C0xeAUYGQa0ETvPYndlaml9Y8H.jpg',
      id: 945729,
      title: 'A Haunting in Venice',
      original_language: 'en',
      original_title: 'A Haunting in Venice',
      overview:
        'Celebrated sleuth Hercule Poirot, now retired and living in self-imposed exile in Venice, reluctantly attends a Halloween séance at a decaying, haunted palazzo. When one of the guests is murdered, the detective is thrust into a sinister world of shadows and secrets.',
      poster_path: '/1Xgjl22MkAZQUavvOeBqRehrvqO.jpg',
      media_type: 'movie',
      genre_ids: [9648, 18, 80],
      popularity: 398.167,
      release_date: '2023-09-13',
      video: false,
      vote_average: 6.789,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: '/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg',
      id: 976573,
      title: 'Elemental',
      original_language: 'en',
      original_title: 'Elemental',
      overview:
        'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
      poster_path: '/6oH378KUfCEitzJkm07r97L0RsZ.jpg',
      media_type: 'movie',
      genre_ids: [16, 35, 10751, 14, 10749],
      popularity: 1241.972,
      release_date: '2023-06-14',
      video: false,
      vote_average: 7.787,
      vote_count: 2020,
    },
    {
      adult: false,
      backdrop_path: '/iOJX54nVAsnPawagFiWXKv1Y6sB.jpg',
      id: 1076364,
      title: "Carl's Date",
      original_language: 'en',
      original_title: "Carl's Date",
      overview:
        "Carl Fredricksen reluctantly agrees to go on a date with a lady friend—but admittedly has no idea how dating works these days. Ever the helpful friend, Dug steps in to calm Carl's pre-date jitters and offer some tried-and-true tips for making friends—if you're a dog.",
      poster_path: '/y8NtM6q3PzntqyNRNw6wgicwRYl.jpg',
      media_type: 'movie',
      genre_ids: [16, 12, 10751],
      popularity: 47.565,
      release_date: '2023-06-15',
      video: false,
      vote_average: 7.848,
      vote_count: 105,
    },
    {
      adult: false,
      backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
      id: 569094,
      title: 'Spider-Man: Across the Spider-Verse',
      original_language: 'en',
      original_title: 'Spider-Man: Across the Spider-Verse',
      overview:
        'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
      poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      media_type: 'movie',
      genre_ids: [16, 28, 12],
      popularity: 694.979,
      release_date: '2023-05-31',
      video: false,
      vote_average: 8.449,
      vote_count: 4193,
    },
    {
      adult: false,
      backdrop_path: '/9m161GawbY3cWxe6txd1NOHTjd0.jpg',
      id: 335977,
      title: 'Indiana Jones and the Dial of Destiny',
      original_language: 'en',
      original_title: 'Indiana Jones and the Dial of Destiny',
      overview:
        "Finding himself in a new era, and approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
      poster_path: '/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg',
      media_type: 'movie',
      genre_ids: [878, 12, 28, 14],
      popularity: 1194.179,
      release_date: '2023-06-28',
      video: false,
      vote_average: 6.67,
      vote_count: 1598,
    },
    {
      adult: false,
      backdrop_path: '/5mzr6JZbrqnqD8rCEvPhuCE5Fw2.jpg',
      id: 615656,
      title: 'Meg 2: The Trench',
      original_language: 'en',
      original_title: 'Meg 2: The Trench',
      overview:
        'An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.',
      poster_path: '/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg',
      media_type: 'movie',
      genre_ids: [28, 878, 27],
      popularity: 2259.905,
      release_date: '2023-08-02',
      video: false,
      vote_average: 6.996,
      vote_count: 1736,
    },
    {
      adult: false,
      backdrop_path: '/xsnpgM2Si1hG7daLP1XE7uAfKKH.jpg',
      id: 1152797,
      title: 'Freestyle',
      original_language: 'pl',
      original_title: 'Freestyle',
      overview:
        'Trying to check out a recording from his debut album, a street rapper and his friend run into trouble when a major drug deal turns into a total disaster for them.',
      poster_path: '/hNPJzlPlIVgTAjb2Mgqwl1QqydK.jpg',
      media_type: 'movie',
      genre_ids: [80, 28, 53],
      popularity: 27.205,
      release_date: '2023-09-13',
      video: false,
      vote_average: 7.192,
      vote_count: 13,
    },
    {
      adult: false,
      backdrop_path: '/qaykuAPezrTTQAWDjP8lLnV3cJx.jpg',
      id: 1015303,
      title: 'Elevator Game',
      original_language: 'en',
      original_title: 'Elevator Game',
      overview:
        'Follows socially awkward teenager Ryan, who discovers that the night his sister disappeared she had played ‘The Elevator Game’ — a ritual conducted in an elevator in which players attempt to travel to another dimension using a set of rules that can be found online. Ignoring warnings, he resolves to follow and find her.',
      poster_path: '/bKQBtrhl4Fnpd0620FeCtX7EpnK.jpg',
      media_type: 'movie',
      genre_ids: [27],
      popularity: 13.681,
      release_date: '2023-07-12',
      video: false,
      vote_average: 3.5,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: '/fgw4rFs4XMWdJTWp1eMacHKQqbZ.jpg',
      id: 603692,
      title: 'John Wick: Chapter 4',
      original_language: 'en',
      original_title: 'John Wick: Chapter 4',
      overview:
        'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
      poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
      media_type: 'movie',
      genre_ids: [28, 53, 80],
      popularity: 542.019,
      release_date: '2023-03-22',
      video: false,
      vote_average: 7.815,
      vote_count: 4486,
    },
    {
      adult: false,
      backdrop_path: '/c6Splshb8lb2Q9OvUfhpqXl7uP0.jpg',
      id: 717930,
      title: 'Kandahar',
      original_language: 'en',
      original_title: 'Kandahar',
      overview:
        'After his mission is exposed, an undercover CIA operative stuck deep in hostile territory in Afghanistan must fight his way out, alongside his Afghan translator, to an extraction point in Kandahar, all whilst avoiding elite enemy forces and foreign spies tasked with hunting them down.',
      poster_path: '/lCanGgsqF4xD2WA5NF8PWeT3IXd.jpg',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 1172.07,
      release_date: '2023-05-25',
      video: false,
      vote_average: 6.727,
      vote_count: 467,
    },
  ]);

  const [upComing, setUpComing] = useState([
    {
      adult: false,
      backdrop_path: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg',
      genre_ids: [35, 12, 14],
      id: 346698,
      original_language: 'en',
      original_title: 'Barbie',
      overview:
        'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
      popularity: 2929.987,
      poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
      release_date: '2023-07-19',
      title: 'Barbie',
      video: false,
      vote_average: 7.3,
      vote_count: 4421,
    },
    {
      adult: false,
      backdrop_path: '/3tzPSJiCPqacAgRsMkMPof2ZinL.jpg',
      genre_ids: [27, 53],
      id: 1008042,
      original_language: 'en',
      original_title: 'Talk to Me',
      overview:
        'When a group of friends discover how to conjure spirits using an embalmed hand, they become hooked on the new thrill, until one of them goes too far and unleashes terrifying supernatural forces.',
      popularity: 2685.799,
      poster_path: '/kdPMUMJzyYAc4roD52qavX0nLIC.jpg',
      release_date: '2023-07-26',
      title: 'Talk to Me',
      video: false,
      vote_average: 7.2,
      vote_count: 455,
    },
    {
      adult: false,
      backdrop_path: '/53z2fXEKfnNg2uSOPss2unPBGX1.jpg',
      genre_ids: [27, 9648, 53],
      id: 968051,
      original_language: 'en',
      original_title: 'The Nun II',
      overview:
        'In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.',
      popularity: 1608.611,
      poster_path: '/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg',
      release_date: '2023-09-06',
      title: 'The Nun II',
      video: false,
      vote_average: 6.7,
      vote_count: 163,
    },
    {
      adult: false,
      backdrop_path: '/jkKVLzLWjSvTnc84VzeljhSy6j8.jpg',
      genre_ids: [10749, 18],
      id: 820525,
      original_language: 'en',
      original_title: 'After Everything',
      overview:
        'Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.',
      popularity: 806.746,
      poster_path: '/gZLGCibvFY4zmt8sWUZcbBTHRtk.jpg',
      release_date: '2023-09-13',
      title: 'After Everything',
      video: false,
      vote_average: 5.6,
      vote_count: 9,
    },
    {
      adult: false,
      backdrop_path: '/w2nFc2Rsm93PDkvjY4LTn17ePO0.jpg',
      genre_ids: [16, 35, 28],
      id: 614930,
      original_language: 'en',
      original_title: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
      overview:
        "After years of being sheltered from the human world, the Turtle brothers set out to win the hearts of New Yorkers and be accepted as normal teenagers through heroic acts. Their new friend April O'Neil helps them take on a mysterious crime syndicate, but they soon get in over their heads when an army of mutants is unleashed upon them.",
      popularity: 841.568,
      poster_path: '/ueO9MYIOHO7M1PiMUeX74uf8fB9.jpg',
      release_date: '2023-07-31',
      title: 'Teenage Mutant Ninja Turtles: Mutant Mayhem',
      video: false,
      vote_average: 7.2,
      vote_count: 441,
    },
    {
      adult: false,
      backdrop_path: '/2ii07lSwHarg0gWnJoCYL3Gyd1j.jpg',
      genre_ids: [35, 12],
      id: 912908,
      original_language: 'en',
      original_title: 'Strays',
      overview:
        'When Reggie is abandoned on the mean city streets by his lowlife owner, Doug, Reggie is certain that his beloved owner would never leave him on purpose. But once Reggie falls in with Bug, a fast-talking, foul-mouthed stray who loves his freedom and believes that owners are for suckers, Reggie finally realizes he was in a toxic relationship and begins to see Doug for the heartless sleazeball that he is.',
      popularity: 714.82,
      poster_path: '/n1hqbSCtyBAxaXEl1Dj3ipXJAJG.jpg',
      release_date: '2023-08-17',
      title: 'Strays',
      video: false,
      vote_average: 7.5,
      vote_count: 259,
    },
    {
      adult: false,
      backdrop_path: '/qEm4FrkGh7kGoEiBOyGYNielYVc.jpg',
      genre_ids: [27, 14],
      id: 635910,
      original_language: 'en',
      original_title: 'The Last Voyage of the Demeter',
      overview:
        'The crew of the merchant ship Demeter attempts to survive the ocean voyage from Carpathia to London as they are stalked each night by a merciless presence onboard the ship.',
      popularity: 539.305,
      poster_path: '/nrtbv6Cew7qC7k9GsYSf5uSmuKh.jpg',
      release_date: '2023-08-09',
      title: 'The Last Voyage of the Demeter',
      video: false,
      vote_average: 7.3,
      vote_count: 580,
    },
    {
      adult: false,
      backdrop_path: '/7I6VUdPj6tQECNHdviJkUHD2u89.jpg',
      genre_ids: [28, 53, 80],
      id: 603692,
      original_language: 'en',
      original_title: 'John Wick: Chapter 4',
      overview:
        'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
      popularity: 542.019,
      poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
      release_date: '2023-03-22',
      title: 'John Wick: Chapter 4',
      video: false,
      vote_average: 7.8,
      vote_count: 4479,
    },
    {
      adult: false,
      backdrop_path: '/h0nmmdFAdBjQttN8Y0q825MWzZp.jpg',
      genre_ids: [28, 53, 80],
      id: 926393,
      original_language: 'en',
      original_title: 'The Equalizer 3',
      overview:
        "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
      popularity: 418.567,
      poster_path: '/p0WBnzgyqxMxbF4UGiqTwBLnwht.jpg',
      release_date: '2023-08-30',
      title: 'The Equalizer 3',
      video: false,
      vote_average: 6.9,
      vote_count: 170,
    },
    {
      adult: false,
      backdrop_path: '/7C0xeAUYGQa0ETvPYndlaml9Y8H.jpg',
      genre_ids: [9648, 18, 80],
      id: 945729,
      original_language: 'en',
      original_title: 'A Haunting in Venice',
      overview:
        'Celebrated sleuth Hercule Poirot, now retired and living in self-imposed exile in Venice, reluctantly attends a Halloween séance at a decaying, haunted palazzo. When one of the guests is murdered, the detective is thrust into a sinister world of shadows and secrets.',
      popularity: 398.167,
      poster_path: '/1Xgjl22MkAZQUavvOeBqRehrvqO.jpg',
      release_date: '2023-09-13',
      title: 'A Haunting in Venice',
      video: false,
      vote_average: 6.7,
      vote_count: 55,
    },
    {
      adult: false,
      backdrop_path: '/ixZzr4PyM2TPs5fka3IJj058WYo.jpg',
      genre_ids: [28, 878, 12],
      id: 565770,
      original_language: 'en',
      original_title: 'Blue Beetle',
      overview:
        'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',
      popularity: 270.638,
      poster_path: '/vNfL4DYnonltukBrrgMmw94zMYL.jpg',
      release_date: '2023-08-16',
      title: 'Blue Beetle',
      video: false,
      vote_average: 6.9,
      vote_count: 357,
    },
    {
      adult: false,
      backdrop_path: '/iEFuHjqrE059SmflBva1JzDJutE.jpg',
      genre_ids: [16, 10751, 28, 14, 10749],
      id: 496450,
      original_language: 'fr',
      original_title: 'Miraculous - le film',
      overview:
        'A life of an ordinary Parisian teenager Marinette goes superhuman when she becomes Ladybug. Bestowed with magical powers of creation, Ladybug must unite with her opposite, Cat Noir, to save Paris as a new villain unleashes chaos unto the city.',
      popularity: 258.515,
      poster_path: '/bBON9XO9Ek0DjRwMBnJNCwC96Cd.jpg',
      release_date: '2023-07-05',
      title: 'Miraculous: Ladybug & Cat Noir, The Movie',
      video: false,
      vote_average: 7.9,
      vote_count: 556,
    },
    {
      adult: false,
      backdrop_path: '/qZOuoBoKCDLSm1EvYz2eBub8Cto.jpg',
      genre_ids: [16, 12, 14, 10751],
      id: 939338,
      original_language: 'fr',
      original_title: 'Pattie et la colère de Poséidon',
      overview:
        'An adventurous mouse sets off to battle dangerous creatures in Ancient Greece, including Poseidon.',
      popularity: 176.042,
      poster_path: '/gVPw9gRPsZZhzY6cIXp6h6nep5M.jpg',
      release_date: '2023-01-25',
      title: 'Epic Tails',
      video: false,
      vote_average: 6.4,
      vote_count: 19,
    },
    {
      adult: false,
      backdrop_path: '/9t0tJXcOdWwwxmGTk112HGDaT0Q.jpg',
      genre_ids: [27, 53],
      id: 890771,
      original_language: 'en',
      original_title: 'The Black Demon',
      overview:
        "Oilman Paul Sturges' idyllic family vacation turns into a nightmare when they encounter a ferocious megalodon shark that will stop at nothing to protect its territory. Stranded and under constant attack, Paul and his family must somehow find a way to get his family back to shore alive before it strikes again in this epic battle between humans and nature.",
      popularity: 127.038,
      poster_path: '/6ecSjKSjgIULyHfrfyyg9vgAI33.jpg',
      release_date: '2023-04-26',
      title: 'The Black Demon',
      video: false,
      vote_average: 6.3,
      vote_count: 490,
    },
    {
      adult: false,
      backdrop_path: '/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg',
      genre_ids: [28, 12, 53],
      id: 299054,
      original_language: 'en',
      original_title: 'Expend4bles',
      overview:
        'Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.',
      popularity: 117.853,
      poster_path: '/nbrqj9q8WubD3QkYm7n3GhjN7kE.jpg',
      release_date: '2023-09-15',
      title: 'Expend4bles',
      video: false,
      vote_average: 8.3,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: '/gknIloEJve4FgAzlKdOUZu1K9HT.jpg',
      genre_ids: [53],
      id: 1109534,
      original_language: 'en',
      original_title: 'The Dive',
      overview:
        'Two sisters go diving at a beautiful, remote location. One of the sisters is struck by a rock, leaving her trapped 28 meters below. With dangerously low levels of oxygen and cold temperatures, it is up to her sister to fight for her life.',
      popularity: 107.215,
      poster_path: '/o43eMkNkWBBsyxEyyUeQwl4AOe.jpg',
      release_date: '2023-08-24',
      title: 'The Dive',
      video: false,
      vote_average: 6.4,
      vote_count: 36,
    },
    {
      adult: false,
      backdrop_path: '/aI7cN9jLpRxdopXSFHEefBRrxyN.jpg',
      genre_ids: [878, 28, 53],
      id: 670292,
      original_language: 'en',
      original_title: 'The Creator',
      overview:
        'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
      popularity: 99.117,
      poster_path: '/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg',
      release_date: '2023-09-27',
      title: 'The Creator',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/yDaMQbBfyGzGWKxUsPMxzWVuJlY.jpg',
      genre_ids: [10751, 16, 18],
      id: 8587,
      original_language: 'en',
      original_title: 'The Lion King',
      overview:
        'A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him, the young prince must decide his fate: Will he remain an outcast or face his demons and become what he needs to be?',
      popularity: 97.923,
      poster_path: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
      release_date: '1994-06-24',
      title: 'The Lion King',
      video: false,
      vote_average: 8.3,
      vote_count: 16947,
    },
    {
      adult: false,
      backdrop_path: '/T5xXoFqyc9jNXZIbH4Sw0jwWjw.jpg',
      genre_ids: [80, 53, 9648],
      id: 605886,
      original_language: 'en',
      original_title: 'Misanthrope',
      overview:
        "Baltimore. New Year's Eve. A talented but troubled police officer is recruited by the FBI's chief investigator to help profile and track down a mass murderer.",
      popularity: 92.993,
      poster_path: '/mFp3l4lZg1NSEsyxKrdi0rNK8r1.jpg',
      release_date: '2023-04-06',
      title: 'To Catch a Killer',
      video: false,
      vote_average: 7,
      vote_count: 495,
    },
    {
      adult: false,
      backdrop_path: '/rXf7ZITGmFdIhnXvknlB9cHqrTr.jpg',
      genre_ids: [35],
      id: 885243,
      original_language: 'fr',
      original_title: 'Juste ciel !',
      overview:
        'Five nuns set their sights on winning the cash prize in a major cycling race to raise money to renovate a dilapidated hospice. The only hitch is that none of them can ride a bicycle.',
      popularity: 77.451,
      poster_path: '/obL1CaAMpa55ue2qTR4rap9hUAE.jpg',
      release_date: '2023-02-15',
      title: 'Oh My Goodness!',
      video: false,
      vote_average: 4.8,
      vote_count: 17,
    },
  ]);

  const [topRated, setTopRated] = useState([
    {
      adult: false,
      backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
      genre_ids: [18, 80],
      id: 238,
      original_language: 'en',
      original_title: 'The Godfather',
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      popularity: 106.932,
      poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
      release_date: '1972-03-14',
      title: 'The Godfather',
      video: false,
      vote_average: 8.7,
      vote_count: 18627,
    },
    {
      adult: false,
      backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
      genre_ids: [18, 80],
      id: 278,
      original_language: 'en',
      original_title: 'The Shawshank Redemption',
      overview:
        'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
      popularity: 94.967,
      poster_path: '/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
      release_date: '1994-09-23',
      title: 'The Shawshank Redemption',
      video: false,
      vote_average: 8.7,
      vote_count: 24593,
    },
    {
      adult: false,
      backdrop_path: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
      genre_ids: [18, 80],
      id: 240,
      original_language: 'en',
      original_title: 'The Godfather Part II',
      overview:
        'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
      popularity: 59.898,
      poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
      release_date: '1974-12-20',
      title: 'The Godfather Part II',
      video: false,
      vote_average: 8.6,
      vote_count: 11254,
    },
    {
      adult: false,
      backdrop_path: '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: 'en',
      original_title: "Schindler's List",
      overview:
        'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
      popularity: 66.089,
      poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
      release_date: '1993-12-15',
      title: "Schindler's List",
      video: false,
      vote_average: 8.6,
      vote_count: 14540,
    },
    {
      adult: false,
      backdrop_path: '/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg',
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: 'hi',
      original_title: 'दिलवाले दुल्हनिया ले जायेंगे',
      overview:
        'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
      popularity: 28.897,
      poster_path: '/ktejodbcdCPXbMMdnpI9BUxW6O8.jpg',
      release_date: '1995-10-20',
      title: 'Dilwale Dulhania Le Jayenge',
      video: false,
      vote_average: 8.6,
      vote_count: 4245,
    },
    {
      adult: false,
      backdrop_path: '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
      genre_ids: [18],
      id: 389,
      original_language: 'en',
      original_title: '12 Angry Men',
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 48.371,
      poster_path: '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
      release_date: '1957-04-10',
      title: '12 Angry Men',
      video: false,
      vote_average: 8.5,
      vote_count: 7620,
    },
    {
      adult: false,
      backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: 'ja',
      original_title: '千と千尋の神隠し',
      overview:
        'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
      popularity: 80.012,
      poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
      release_date: '2001-07-20',
      title: 'Spirited Away',
      video: false,
      vote_average: 8.5,
      vote_count: 14869,
    },
    {
      adult: false,
      backdrop_path: '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: 'ko',
      original_title: '기생충',
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 69.628,
      poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
      release_date: '2019-05-30',
      title: 'Parasite',
      video: false,
      vote_average: 8.5,
      vote_count: 16370,
    },
    {
      adult: false,
      backdrop_path: '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
      genre_ids: [10749, 16, 18],
      id: 372058,
      original_language: 'ja',
      original_title: '君の名は。',
      overview:
        'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
      popularity: 74.368,
      poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg',
      release_date: '2016-08-26',
      title: 'Your Name.',
      video: false,
      vote_average: 8.5,
      vote_count: 10260,
    },
    {
      adult: false,
      backdrop_path: '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: 'en',
      original_title: 'The Dark Knight',
      overview:
        'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
      popularity: 90.804,
      poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      release_date: '2008-07-14',
      title: 'The Dark Knight',
      video: false,
      vote_average: 8.5,
      vote_count: 30544,
    },
    {
      adult: false,
      backdrop_path: '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: 'en',
      original_title: 'The Green Mile',
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 62.108,
      poster_path: '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
      release_date: '1999-12-10',
      title: 'The Green Mile',
      video: false,
      vote_average: 8.5,
      vote_count: 15892,
    },
    {
      adult: false,
      backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
      genre_ids: [53, 80],
      id: 680,
      original_language: 'en',
      original_title: 'Pulp Fiction',
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 63.954,
      poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
      release_date: '1994-09-10',
      title: 'Pulp Fiction',
      video: false,
      vote_average: 8.5,
      vote_count: 25825,
    },
    {
      adult: false,
      backdrop_path: '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: 'en',
      original_title: 'Forrest Gump',
      overview:
        'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
      popularity: 62.73,
      poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
      release_date: '1994-06-23',
      title: 'Forrest Gump',
      video: false,
      vote_average: 8.5,
      vote_count: 25350,
    },
    {
      adult: false,
      backdrop_path: '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: 'en',
      original_title: 'The Lord of the Rings: The Return of the King',
      overview:
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
      popularity: 90.715,
      poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
      release_date: '2003-12-01',
      title: 'The Lord of the Rings: The Return of the King',
      video: false,
      vote_average: 8.5,
      vote_count: 22222,
    },
    {
      adult: false,
      backdrop_path: '/eoCSp75lxatmIa6aGqfnzwtbttd.jpg',
      genre_ids: [37],
      id: 429,
      original_language: 'it',
      original_title: 'Il buono, il brutto, il cattivo',
      overview:
        'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
      popularity: 51.07,
      poster_path: '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
      release_date: '1966-12-23',
      title: 'The Good, the Bad and the Ugly',
      video: false,
      vote_average: 8.5,
      vote_count: 7719,
    },
    {
      adult: false,
      backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg',
      genre_ids: [18, 80],
      id: 769,
      original_language: 'en',
      original_title: 'GoodFellas',
      overview:
        'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
      popularity: 50.111,
      poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
      release_date: '1990-09-12',
      title: 'GoodFellas',
      video: false,
      vote_average: 8.5,
      vote_count: 11687,
    },
    {
      adult: false,
      backdrop_path: '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
      genre_ids: [18, 10749],
      id: 11216,
      original_language: 'it',
      original_title: 'Nuovo Cinema Paradiso',
      overview:
        "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
      popularity: 25.822,
      poster_path: '/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg',
      release_date: '1988-11-17',
      title: 'Cinema Paradiso',
      video: false,
      vote_average: 8.5,
      vote_count: 3933,
    },
    {
      adult: false,
      backdrop_path: '/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg',
      genre_ids: [35, 18],
      id: 637,
      original_language: 'it',
      original_title: 'La vita è bella',
      overview:
        'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
      popularity: 42.114,
      poster_path: '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
      release_date: '1997-12-20',
      title: 'Life Is Beautiful',
      video: false,
      vote_average: 8.5,
      vote_count: 12186,
    },
    {
      adult: false,
      backdrop_path: '/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg',
      genre_ids: [16, 18, 10752],
      id: 12477,
      original_language: 'ja',
      original_title: '火垂るの墓',
      overview:
        'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
      popularity: 0.6,
      poster_path: '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
      release_date: '1988-04-16',
      title: 'Grave of the Fireflies',
      video: false,
      vote_average: 8.5,
      vote_count: 4835,
    },
    {
      adult: false,
      backdrop_path: '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
      genre_ids: [28, 18],
      id: 346,
      original_language: 'ja',
      original_title: '七人の侍',
      overview:
        "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
      popularity: 32.452,
      poster_path: '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
      release_date: '1954-04-26',
      title: 'Seven Samurai',
      video: false,
      vote_average: 8.5,
      vote_count: 3209,
    },
  ]);

  return (
    <View className="flex-1 bg-white">
      <SafeAreaView className="">
        <View className="flex-row justify-between items-center mx-4">
          <Text className="text-neutral-800 text-3xl font-bold">
            <Text style={styles.text}>U</Text>demig
          </Text>
          <TouchableOpacity onPress={() => navigation.navigate('Search')}>
            <MagnifyingGlassIcon size="30" strokeWidth={2} color={'black'} />
          </TouchableOpacity>
        </View>
        {loading ? (
          <Loading />
        ) : (
          <ScrollView showsVerticalScrollIndicator={false}>
            <TrendingMovies data={trending} />
            <MovieList data={upComing} title={'Upcoming'} />
            <MovieList data={topRated} title={'Top Rated'} />
          </ScrollView>
        )}
      </SafeAreaView>
    </View>
  );
}
